# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppLogisticMap <- function(x = 3.6, y = 3.72, z = 3.68, step = 20L, alpha_x = 0.625, alpha_y = 0.77, alpha_z = 0.55, beta_xy = 0.05, beta_xz = 0.05, beta_yx = 0.4, beta_yz = 0.4, beta_zx = 0.65, beta_zy = 0.65, escape_threshold = 1e10) {
    .Call(`_tEDM_RcppLogisticMap`, x, y, z, step, alpha_x, alpha_y, alpha_z, beta_xy, beta_xz, beta_yx, beta_yz, beta_zx, beta_zy, escape_threshold)
}

RcppEmbed <- function(vec, E = 3L, tau = 1L, style = 0L) {
    .Call(`_tEDM_RcppEmbed`, vec, E, tau, style)
}

RcppSimplexForecast <- function(source, target, E, tau, lib, pred, num_neighbors) {
    .Call(`_tEDM_RcppSimplexForecast`, source, target, E, tau, lib, pred, num_neighbors)
}

RcppSMapForecast <- function(source, target, E, tau, lib, pred, num_neighbors, theta) {
    .Call(`_tEDM_RcppSMapForecast`, source, target, E, tau, lib, pred, num_neighbors, theta)
}

RcppIntersectionCardinality <- function(source, target, E, tau, lib, pred, num_neighbors = 4L, n_excluded = 0L, threads = 8L, parallel_level = 0L) {
    .Call(`_tEDM_RcppIntersectionCardinality`, source, target, E, tau, lib, pred, num_neighbors, n_excluded, threads, parallel_level)
}

RcppMVE4TS <- function(x, y, lib, pred, E, tau, b, top, nvar, threads) {
    .Call(`_tEDM_RcppMVE4TS`, x, y, lib, pred, E, tau, b, top, nvar, threads)
}

RcppFNN4TS <- function(vec, rt, eps, lib, pred, E, tau = 0L, threads = 8L, parallel_level = 0L) {
    .Call(`_tEDM_RcppFNN4TS`, vec, rt, eps, lib, pred, E, tau, threads, parallel_level)
}

RcppSimplex4TS <- function(source, target, lib, pred, E, b, tau = 0L, threads = 8L) {
    .Call(`_tEDM_RcppSimplex4TS`, source, target, lib, pred, E, b, tau, threads)
}

RcppSMap4TS <- function(source, target, lib, pred, theta, E = 3L, tau = 0L, b = 4L, threads = 8L) {
    .Call(`_tEDM_RcppSMap4TS`, source, target, lib, pred, theta, E, tau, b, threads)
}

RcppMultiSimplex4TS <- function(source, target, lib, pred, E, b, tau = 0L, threads = 8L) {
    .Call(`_tEDM_RcppMultiSimplex4TS`, source, target, lib, pred, E, b, tau, threads)
}

RcppIC4TS <- function(source, target, lib, pred, E, b, tau = 0L, exclude = 0L, threads = 8L, parallel_level = 0L) {
    .Call(`_tEDM_RcppIC4TS`, source, target, lib, pred, E, b, tau, exclude, threads, parallel_level)
}

RcppCCM <- function(x, y, libsizes, lib, pred, E = 3L, tau = 0L, b = 4L, simplex = TRUE, theta = 0, threads = 8L, parallel_level = 0L, progressbar = FALSE) {
    .Call(`_tEDM_RcppCCM`, x, y, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, progressbar)
}

RcppPCM <- function(x, y, z, libsizes, lib, pred, E, tau, b, simplex = TRUE, theta = 0, threads = 8L, parallel_level = 0L, cumulate = FALSE, progressbar = FALSE) {
    .Call(`_tEDM_RcppPCM`, x, y, z, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, cumulate, progressbar)
}

RcppCMC <- function(x, y, libsizes, lib, pred, E, tau, b, r = 0L, threads = 8L, parallel_level = 0L, progressbar = FALSE) {
    .Call(`_tEDM_RcppCMC`, x, y, libsizes, lib, pred, E, tau, b, r, threads, parallel_level, progressbar)
}

RcppMultispatialCCM <- function(x, y, libsizes, E = 3L, tau = 0L, b = 4L, boot = 299L, seed = 42L, threads = 8L, parallel_level = 0L, progressbar = FALSE) {
    .Call(`_tEDM_RcppMultispatialCCM`, x, y, libsizes, E, tau, b, boot, seed, threads, parallel_level, progressbar)
}

DetectMaxNumThreads <- function() {
    .Call(`_tEDM_DetectMaxNumThreads`)
}

OptEmbedDim <- function(Emat) {
    .Call(`_tEDM_OptEmbedDim`, Emat)
}

OptThetaParm <- function(Thetamat) {
    .Call(`_tEDM_OptThetaParm`, Thetamat)
}

OptICparm <- function(Emat) {
    .Call(`_tEDM_OptICparm`, Emat)
}

MatNotNAIndice <- function(mat, byrow = TRUE) {
    .Call(`_tEDM_MatNotNAIndice`, mat, byrow)
}

RcppFactorial <- function(n) {
    .Call(`_tEDM_RcppFactorial`, n)
}

RcppCombine <- function(n, k) {
    .Call(`_tEDM_RcppCombine`, n, k)
}

RcppDigamma <- function(x) {
    .Call(`_tEDM_RcppDigamma`, x)
}

RcppLog <- function(x, base = 10) {
    .Call(`_tEDM_RcppLog`, x, base)
}

RcppMedian <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMedian`, vec, NA_rm)
}

RcppMean <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMean`, vec, NA_rm)
}

RcppMin <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMin`, vec, NA_rm)
}

RcppMax <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMax`, vec, NA_rm)
}

RcppSum <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppSum`, vec, NA_rm)
}

RcppVariance <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppVariance`, vec, NA_rm)
}

RcppCovariance <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_tEDM_RcppCovariance`, vec1, vec2, NA_rm)
}

RcppMAE <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMAE`, vec1, vec2, NA_rm)
}

RcppRMSE <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_tEDM_RcppRMSE`, vec1, vec2, NA_rm)
}

RcppCumSum <- function(vec) {
    .Call(`_tEDM_RcppCumSum`, vec)
}

RcppAbsDiff <- function(vec1, vec2) {
    .Call(`_tEDM_RcppAbsDiff`, vec1, vec2)
}

RcppSumNormalize <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppSumNormalize`, vec, NA_rm)
}

RcppArithmeticSeq <- function(from, to, length_out) {
    .Call(`_tEDM_RcppArithmeticSeq`, from, to, length_out)
}

RcppPearsonCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_tEDM_RcppPearsonCor`, y, y_hat, NA_rm)
}

RcppSpearmanCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_tEDM_RcppSpearmanCor`, y, y_hat, NA_rm)
}

RcppKendallCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_tEDM_RcppKendallCor`, y, y_hat, NA_rm)
}

RcppPartialCor <- function(y, y_hat, controls, NA_rm = FALSE, linear = FALSE, pinv_tol = 1e-10) {
    .Call(`_tEDM_RcppPartialCor`, y, y_hat, controls, NA_rm, linear, pinv_tol)
}

RcppPartialCorTrivar <- function(y, y_hat, control, NA_rm = FALSE, linear = FALSE, pinv_tol = 1e-10) {
    .Call(`_tEDM_RcppPartialCorTrivar`, y, y_hat, control, NA_rm, linear, pinv_tol)
}

RcppCorSignificance <- function(r, n, k = 0L) {
    .Call(`_tEDM_RcppCorSignificance`, r, n, k)
}

RcppCorConfidence <- function(r, n, k = 0L, level = 0.05) {
    .Call(`_tEDM_RcppCorConfidence`, r, n, k, level)
}

RcppMeanCorSignificance <- function(r, n, k = 0L) {
    .Call(`_tEDM_RcppMeanCorSignificance`, r, n, k)
}

RcppMeanCorConfidence <- function(r, n, k = 0L, level = 0.05) {
    .Call(`_tEDM_RcppMeanCorConfidence`, r, n, k, level)
}

RcppDeLongAUCConfidence <- function(cases, controls, direction, level = 0.05) {
    .Call(`_tEDM_RcppDeLongAUCConfidence`, cases, controls, direction, level)
}

RcppCMCTest <- function(cases, direction, level = 0.05, num_samples = 0L) {
    .Call(`_tEDM_RcppCMCTest`, cases, direction, level, num_samples)
}

RcppDistance <- function(vec1, vec2, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_tEDM_RcppDistance`, vec1, vec2, L1norm, NA_rm)
}

RcppKNearestDistance <- function(vec1, k, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_tEDM_RcppKNearestDistance`, vec1, k, L1norm, NA_rm)
}

RcppMatDistance <- function(mat, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMatDistance`, mat, L1norm, NA_rm)
}

RcppNeighborsNum <- function(vec, radius, equal = FALSE, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_tEDM_RcppNeighborsNum`, vec, radius, equal, L1norm, NA_rm)
}

RcppKNNIndice <- function(embedding_space, target_idx, k, lib) {
    .Call(`_tEDM_RcppKNNIndice`, embedding_space, target_idx, k, lib)
}

RcppDistKNNIndice <- function(dist_mat, target_idx, k, lib) {
    .Call(`_tEDM_RcppDistKNNIndice`, dist_mat, target_idx, k, lib)
}

RcppDistSortedIndice <- function(dist_mat, lib, k, include_self = FALSE) {
    .Call(`_tEDM_RcppDistSortedIndice`, dist_mat, lib, k, include_self)
}

RcppMatKNNeighbors <- function(embeddings, lib, k, threads = 8L, L1norm = FALSE) {
    .Call(`_tEDM_RcppMatKNNeighbors`, embeddings, lib, k, threads, L1norm)
}

RcppLinearTrendRM <- function(vec, xcoord, ycoord, NA_rm = FALSE) {
    .Call(`_tEDM_RcppLinearTrendRM`, vec, xcoord, ycoord, NA_rm)
}

RcppSVD <- function(X) {
    .Call(`_tEDM_RcppSVD`, X)
}

RcppDeLongPlacements <- function(cases, controls, direction) {
    .Call(`_tEDM_RcppDeLongPlacements`, cases, controls, direction)
}

