# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppEmbed <- function(vec, E, tau = 0L) {
    .Call(`_tEDM_RcppEmbed`, vec, E, tau)
}

RcppSimplexForecast <- function(source, target, E, tau, lib, pred, num_neighbors) {
    .Call(`_tEDM_RcppSimplexForecast`, source, target, E, tau, lib, pred, num_neighbors)
}

RcppSMapForecast <- function(source, target, E, tau, lib, pred, num_neighbors, theta) {
    .Call(`_tEDM_RcppSMapForecast`, source, target, E, tau, lib, pred, num_neighbors, theta)
}

RcppCCM <- function(x, y, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, progressbar) {
    .Call(`_tEDM_RcppCCM`, x, y, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, progressbar)
}

RcppFactorial <- function(n) {
    .Call(`_tEDM_RcppFactorial`, n)
}

RcppCombine <- function(n, k) {
    .Call(`_tEDM_RcppCombine`, n, k)
}

RcppDigamma <- function(x) {
    .Call(`_tEDM_RcppDigamma`, x)
}

RcppLog <- function(x, base = 10) {
    .Call(`_tEDM_RcppLog`, x, base)
}

RcppMedian <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMedian`, vec, NA_rm)
}

RcppMean <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMean`, vec, NA_rm)
}

RcppMin <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMin`, vec, NA_rm)
}

RcppMax <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMax`, vec, NA_rm)
}

RcppSum <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppSum`, vec, NA_rm)
}

RcppVariance <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppVariance`, vec, NA_rm)
}

RcppCovariance <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_tEDM_RcppCovariance`, vec1, vec2, NA_rm)
}

RcppMAE <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMAE`, vec1, vec2, NA_rm)
}

RcppRMSE <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_tEDM_RcppRMSE`, vec1, vec2, NA_rm)
}

RcppCumSum <- function(vec) {
    .Call(`_tEDM_RcppCumSum`, vec)
}

RcppAbsDiff <- function(vec1, vec2) {
    .Call(`_tEDM_RcppAbsDiff`, vec1, vec2)
}

RcppSumNormalize <- function(vec, NA_rm = FALSE) {
    .Call(`_tEDM_RcppSumNormalize`, vec, NA_rm)
}

RcppArithmeticSeq <- function(from, to, length_out) {
    .Call(`_tEDM_RcppArithmeticSeq`, from, to, length_out)
}

RcppPearsonCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_tEDM_RcppPearsonCor`, y, y_hat, NA_rm)
}

RcppSpearmanCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_tEDM_RcppSpearmanCor`, y, y_hat, NA_rm)
}

RcppKendallCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_tEDM_RcppKendallCor`, y, y_hat, NA_rm)
}

RcppPartialCor <- function(y, y_hat, controls, NA_rm = FALSE, linear = FALSE) {
    .Call(`_tEDM_RcppPartialCor`, y, y_hat, controls, NA_rm, linear)
}

RcppPartialCorTrivar <- function(y, y_hat, control, NA_rm = FALSE, linear = FALSE) {
    .Call(`_tEDM_RcppPartialCorTrivar`, y, y_hat, control, NA_rm, linear)
}

RcppCorSignificance <- function(r, n, k = 0L) {
    .Call(`_tEDM_RcppCorSignificance`, r, n, k)
}

RcppCorConfidence <- function(r, n, k = 0L, level = 0.05) {
    .Call(`_tEDM_RcppCorConfidence`, r, n, k, level)
}

RcppDeLongAUCConfidence <- function(cases, controls, direction, level = 0.05) {
    .Call(`_tEDM_RcppDeLongAUCConfidence`, cases, controls, direction, level)
}

RcppCMCTest <- function(cases, direction, level = 0.05, num_samples = 0L) {
    .Call(`_tEDM_RcppCMCTest`, cases, direction, level, num_samples)
}

RcppDistance <- function(vec1, vec2, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_tEDM_RcppDistance`, vec1, vec2, L1norm, NA_rm)
}

RcppKNearestDistance <- function(vec1, k, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_tEDM_RcppKNearestDistance`, vec1, k, L1norm, NA_rm)
}

RcppMatDistance <- function(mat, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_tEDM_RcppMatDistance`, mat, L1norm, NA_rm)
}

RcppNeighborsNum <- function(vec, radius, equal = FALSE, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_tEDM_RcppNeighborsNum`, vec, radius, equal, L1norm, NA_rm)
}

RcppKNNIndice <- function(embedding_space, target_idx, k, lib) {
    .Call(`_tEDM_RcppKNNIndice`, embedding_space, target_idx, k, lib)
}

RcppDistKNNIndice <- function(dist_mat, target_idx, k, lib) {
    .Call(`_tEDM_RcppDistKNNIndice`, dist_mat, target_idx, k, lib)
}

RcppLinearTrendRM <- function(vec, xcoord, ycoord, NA_rm = FALSE) {
    .Call(`_tEDM_RcppLinearTrendRM`, vec, xcoord, ycoord, NA_rm)
}

RcppSVD <- function(X) {
    .Call(`_tEDM_RcppSVD`, X)
}

RcppDeLongPlacements <- function(cases, controls, direction) {
    .Call(`_tEDM_RcppDeLongPlacements`, cases, controls, direction)
}

